---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Stop Tomcat
    shell: /etc/init.d/tomcatstop
  - name: Clean the existing war file
    file:
      path: /root/apache-tomcat-8.5.51/webapps/goldeploy.war
      state: absent    
  - name: Deploy War File
    get_url:
       url: http://3.136.106.71:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /root/apache-tomcat-8.5.51/webapps/goldeploy
  - name: Start Tomcat
    shell: /etc/init.d/tomcatstart
 
